-- AC 06 - 16/09/2018
-- CURSO: ADS 2A
-- ALUNOS:
--NATHALIA CASTILHO ESCARLATE - RA 1800179, 
--TIBÉRIO CRUZ - RA 1800110;

CREATE TABLE TB_UNIDADES
(
COD_UNIDADE INT IDENTITY(1,1) NOT NULL,
NOME_UNIDADE VARCHAR(200) NOT NULL

CONSTRAINT [PK_TB_UNIDADES] PRIMARY KEY (COD_UNIDADE) 

);

INSERT INTO TB_UNIDADES
(NOME_UNIDADE)
VALUES
('PEÇAS'),
('METROS'),
('QUILOGRAMAS'),
('DÚZIAS'),
('PACOTE'),
('CAIXA');

CREATE TABLE TB_CATEGORIAS
(
COD_CATEGORIA INT IDENTITY(1,1) NOT NULL,
NOME_CATEGORIA VARCHAR (500) NOT NULL,

CONSTRAINT [PK_TB_CATEGORIAS] PRIMARY KEY (COD_CATEGORIA) 
);

INSERT INTO TB_CATEGORIAS
(NOME_CATEGORIA)
VALUES
('MOUSE'),
('PEN-DRIVE'),
('MONITOR DE VIDEO'),
('TECLADO'),
('CPU'),
('CABO DE REDE');

CREATE TABLE TB_PRODUTOS
(
COD_PRODUTO INT IDENTITY(1,1) NOT NULL,
NOME_PRODUTO VARCHAR(200) NOT NULL,
COD_UNIDADE INT NOT NULL,
COD_CATEGORIA INT NOT NULL,
QTDE_ESTOQUE INT NOT NULL,
QTDE_MIN INT NOT NULL,
PRECO_CUSTO MONEY NOT NULL,
PRECO_VENDA MONEY NOT NULL,
CARACTERISTICAS_TECNICAS VARCHAR (500),

CONSTRAINT [PK_COD_PRODUTO] PRIMARY KEY (COD_PRODUTO),
CONSTRAINT FK_PRODUTOS_COD_UNIDADE FOREIGN KEY(COD_UNIDADE) REFERENCES [dbo].[TB_UNIDADES] (COD_UNIDADE),
CONSTRAINT FK_PRODUTOS_COD_CATEGORIA FOREIGN KEY(COD_CATEGORIA) REFERENCES [dbo].[TB_CATEGORIAS] (COD_CATEGORIA)
);

INSERT INTO [dbo].[TB_PRODUTOS]
(NOME_PRODUTO,COD_UNIDADE,COD_CATEGORIA,QTDE_ESTOQUE,QTDE_MIN,PRECO_CUSTO,PRECO_VENDA)
VALUES

('Caneta Azul',1,1,150,40,0.5,0.75),
('Caneta Verde',1,1,50,40,0.5,0.75),
('Caneta Vermelha',1,1,80,35,0.5,0.75),
('Lápis',1,1,400,80,0.5,0.8),
('Régua',1,1,40,10,1,1.5);


-- executou-se script_tabelas.sql

UPDATE TB_PRODUTO
SET PRECO_CUSTO = PRECO_CUSTO * 1.15
WHERE COD_TIPO=2

UPDATE TB_PRODUTO
SET PRECO_VENDA = PRECO_VENDA * 1.3
WHERE COD_TIPO=2

UPDATE TB_PRODUTO
SET IPI = 5 WHERE COD_TIPO=3

UPDATE TB_PRODUTO
SET QTD_MINIMA=QTD_MINIMA*0.9


UPDATE TB_CLIENTE
SET ENDERECO = 'AV. CELSO GARCIA,1234',
    BAIRRO   = 'TATUAPE',
    CIDADE   = 'SÃO PAULO',
	ESTADO	 = 'SP',
	CEP		= 03407080
WHERE [CODCLI] = 11

UPDATE TB_CLIENTE
SET ENDERECO=END_COB,
	BAIRRO=BAI_COB,
	CIDADE=CID_COB,
	ESTADO=EST_COB,
	CEP=CEP_COB
WHERE CODCLI = 13

UPDATE TB_CLIENTE 
SET ICMS=12
WHERE ESTADO IN('RJ','RO','AC','RR','MG','PR','SC','RS','MS','MT')

UPDATE TB_CLIENTE 
SET ICMS=18
WHERE ESTADO IN('SP')

SELECT * FROM TB_CLIENTE
UPDATE TB_CLIENTE 
SET ICMS=7
WHERE ESTADO NOT IN('RJ','RO','AC','RR','MG','PR','SC','RS','MS','MT','SP')

UPDATE TB_ITENSPEDIDO
SET DESCONTO = 7
WHERE ID_PRODUTO =8 AND DATA_ENTREGA > '20070101' AND DATA_ENTREGA < '20070131' AND QUANTIDADE > 1000

UPDATE TB_ITENSPEDIDO
SET DESCONTO = 0
WHERE  QUANTIDADE < 1000 AND DATA_ENTREGA > '20070601' AND DESCONTO >0

SELECT * 
INTO VENDEDORES_TMP 
FROM TB_VENDEDOR

DELETE VENDEDORES_TMP  WHERE CODVEN >5

SELECT * 
INTO COPIA_PEDIDOS
FROM TB_PEDIDO

DELETE COPIA_PEDIDOS WHERE CODVEN=2

DELETE COPIA_PEDIDOS WHERE DATA_EMISSAO> '20070101' AND DATA_EMISSAO < '20070630'

DELETE COPIA_PEDIDOS