CREATE TABLE TABELACAR
(
	COD_CARGO INT,
	CARGO VARCHAR(30),
	SALARIO_INIC  MONEY,

	CONSTRAINT [PK_TABELACAR] PRIMARY KEY (COD_CARGO)

);

CREATE TABLE TABELADEP
(	
	COD_DEPTO INT,
	DEPTO VARCHAR(40),

	CONSTRAINT [PK_TABELADEP] PRIMARY KEY (COD_DEPTO)

);

	CREATE TABLE EMPREGADOS
	( 
		CODFUN INT IDENTITY NOT NULL,
		NOME varchar(60) NOT NULL,
		COD_DEPTO int NULL,
		COD_CARGO int NULL,
		NUM_DEPEND TINYINT NULL,
		DATA_NASCIMENTO date NOT NULL,
		DATA_ADMISSAO date NOT NULL,
		SALARIO money NOT NULL,
		SINDICALIZADO BIT NULL,
		OBS varchar(60) NULL,

		CONSTRAINT [PK_EMPREGADOS] PRIMARY KEY (CODFUN),

		CONSTRAINT FK_EMPREGADOS_COD_DEPTO 
			FOREIGN KEY (COD_DEPTO)
			REFERENCES TABELADEP (COD_DEPTO),
			
		CONSTRAINT FK_EMPREGADOS_TABELACAR 
			FOREIGN KEY (COD_CARGO)
			REFERENCES TABELACAR (COD_CARGO), 			 
	);
			
CREATE TABLE DEPENDENTES
(
	NOME VARCHAR(60),
	DATA_NASCIMENTO DATE,
	CODFUN INT IDENTITY NOT NULL,
	CODDEP int NOT NULL,

	CONSTRAINT [PK_DEPENDENTES] PRIMARY KEY (CODDEP),

	CONSTRAINT FK_COD_FUN FOREIGN KEY (CODFUN)
	REFERENCES EMPREGADOS (CODFUN),

);

