--AC03 ---- ALUNA NATHALIA CASTILHO ESCARLATE ---- RA 1800179 ---- TURMA: ADS 2A

-- ALTERAÇÕES EM EMPREGADOS
ALTER TABLE [dbo].[EMPREGADOS]
ADD 
	CONSTRAINT CK_SINDICALIZADO check ([SINDICALIZADO] = 'S' OR [SINDICALIZADO] = 'N'),
	CONSTRAINT CK_DATA_NASCIMENTO Check (DATA_NASCIMENTO BETWEEN '1900/01/01' AND '2500/12/31'), 
	CONSTRAINT CK_SALARIO Check ([SALARIO] >= 500)

-- EXCLUIR A COLUNA OBS
ALTER TABLE [dbo].[EMPREGADOS] DROP COLUMN OBS

-- SALÁRIO_INIC OBRIGATÓRIO
ALTER TABLE [dbo].[TABELACAR] ALTER COLUMN SALARIO_INIC NUMERIC(10,2) NOT NULL

--TROCAR O DATA TYPE DA COLUNA DATA_NASCIMENTO PARA DATE
ALTER TABLE [dbo].[DEPENDENTES] ALTER COLUMN DATA_NASCIMENTO DATE NOT NULL
		
--INCLUIR A COLUNA ANDAR DATA TYPE TINYINT
ALTER TABLE [dbo].[TABELADEP] ADD ANDAR TINYINT NOT NULL	
	
